CREATE TABLE IF NOT EXISTS Post (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CreatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
	Title TEXT NOT NULL,
	Content TEXT NOT NULL,
	User_id INTEGER ,
	Like INTEGER ,
	Dislike INTEGER ,
	FOREIGN KEY (User_id) REFERENCES User (Id)
)